Make gas estimating usage in tx and pass it to RawTransaction
unordered-set/LayerZero-python-aptos pull request #10
Opened 2023-07-23 19:21 UTC by bobu4

Extend usage of simulate_transaction with additional gas_estimating request parameters.

2023-07-27 06:36 UTC, unordered-set commented
Thanks for the pull request! Seems reasonable

2023-07-27 06:37 UTC, unordered-set commented
@ikapeykin LGTM, would you mind to retest it and merge? TY

2023-07-27 06:53 UTC, bobu4 commented
You also need to rebuild your project, because new version of aptos python sdk support only async usage.

2023-07-27 21:35 UTC, ikapeykin commented
Hi @bobu4! Thank you for contributing. Let me validate it in mainnet and I'll back :) 

https://github.com/web3engineering/LayerZero-python-aptos/issues/9

2023-07-28 00:45 UTC, ikapeykin requested changes

2023-07-28 00:45 UTC, ikapeykin commented on src/sdk/aptos_sdk.py
> +        if response.status_code >= 400:
Hi @bobu4, 

I just validated your code. Everything looks good, but there was broken `submit_transaction` method. I resolved this issue, could you please replace the code with the next one?

```python
    def send_and_submit_transaction(self, payload: EntryFunction) -> str:
        GAS_SAFETY_FACTOR = 0.2  # 20%
        raw_transaction = self.client.create_bcs_transaction(
            self.account, TransactionPayload(payload)
        )
        simulated_transaction = self.simulate_transaction_with_gas_estimate(
            transaction=raw_transaction,
        )

        if not simulated_transaction[0]["success"]:  # noqa
            raise ValueError(simulated_transaction[0]["vm_status"])  # noqa

        self.client.client_config.max_gas_amount = int(
            int(simulated_transaction[0]['gas_used'], base=10) * (1 + GAS_SAFETY_FACTOR)
        )

        signed_transaction = self.client.create_bcs_signed_transaction(
            self.account, TransactionPayload(payload)
        )
        txn = self.client.submit_bcs_transaction(signed_transaction)
        self.client.wait_for_transaction(txn)
        return txn

    def simulate_transaction_with_gas_estimate(
        self,
        transaction: RawTransaction
    ) -> Dict[str, Any]:
        authenticator = Authenticator(
            Ed25519Authenticator(
                self.account.public_key(),
                ed25519.Signature(b"\x00" * 64),
            )
        )
        signed_transaction = SignedTransaction(transaction, authenticator)
        params = {
            'estimate_gas_unit_price': "true",
            'estimate_max_gas_amount': "true"
        }
        headers = {
            "Content-Type": "application/x.aptos.signed_transaction+bcs"
        }
        response = self.client.client.post(
            f"{self.client.base_url}/transactions/simulate",
            headers=headers,
            data=signed_transaction.bytes(),
            params=params
        )
        if response.status_code >= 400:
            raise ApiError(response.text, response.status_code)

        return response.json()
```

Let me know as you'll have a chance to update it in your branch, so I'll be able to approve it and merge 

This is awesome btw, stellar work <3

2023-07-28 00:46 UTC, ikapeykin commented on src/sdk/aptos_sdk.py
> +        if response.status_code >= 400:
There is full `aptos_sdk.py` file with some updates:

https://gist.github.com/ikapeykin/a29669b2dca41c7d79b7d8490cd4789d

2023-07-28 00:50 UTC, ikapeykin commented on src/sdk/aptos_sdk.py
> +        if response.status_code >= 400:
I will be happy to wait for you to make changes so that we can change this code and you will be displayed in the code contributors

2023-07-28 06:57 UTC, ikapeykin approved these changes

2023-07-28 06:57 UTC, merged

2023-07-28 07:00 UTC, ikapeykin commented
Thank you for your contribution @bobu4! It's a really great job. We appreciate it 

Welcome to the contributors of our project :)

2023-07-28 07:06 UTC, ikapeykin commented
> You also need to rebuild your project, because new version of aptos python sdk support only async usage.

Massive thanks to you! 

I've created issue related to these changes: https://github.com/web3engineering/LayerZero-python-aptos/issues/11 

So will take it in progress soon. Feel free to join us in contributing :)